### PR TITLE
Create property for nested property

### PR DESCRIPTION
**Pull request by andrelec1**
Fix error if you try to asign nested property in empty model.

### CODE REVIEW

**Comment by wotamann** [comment]
> 
> 
> Fix error if you try to asign nested property in empty model.

Can you give me an example where the error occurs

**Comment by andrelec1** [comment]
use schema with a nested property like: 

```js
      schema: {
        'nested.name': {
          flex: 12,
          label: 'name',
          type: 'text',
        },
      }
```
provide a empty model  `model = {}` ....
Get error that you can't assign name to undefined ...

**Comment by wotamann** [comment]
`'nested.name' `is not a nested property, but a property name containing a dot. 

On the console, try

`let obj = { 'nested.name': 'value' }  `
calling 
`schema.nested.name`
leads to 
`Uncaught TypeError: Cannot read property 'name' of undefined`

A nested property would look like this 
`obj = { nested: {name: 'value' }`
calling 
`obj.nested.name`
leads to 
`"value"`

**Comment by andrelec1** [comment]
So how i define my schema for `obj.nested.name` ?

And why you split / iterate on the property ? 
(https://github.com/wotamann/vuetify-form-base/blob/master/dist/src/vFormBase.vue#L998)

image
You have to define the nested object before asign a property on it ...

**Pull request closed without merging**
